### ISSUE TITLE
Dark mode warning stuck behind preference window

### ISSUE THREAD

**Issue by Minh-Than** [oriedita/oriedita#286]
After making a pull request #285 , I'm still stumped on trying to fix the dark mode warning not being able to show itself in front of the preference window. Any help, especially from @qurben is highly appreciated.

![image](https://user-images.githubusercontent.com/94136126/222322579-a66dcb9a-e131-4529-b219-4934cb32ffdc.png)

**Comment by qurben** [comment]
Looks like a Mac issue :(

On windows it works fine:
![java_2023-03-02_18-37-09](https://user-images.githubusercontent.com/589651/222507687-1d4733f6-b423-4eab-8817-c1e3f5a2088f.png)

**Comment by Minh-Than** [comment]
Oh great :)
Need a specific mac label at this point.
