### ISSUE TITLE
Oriedita freezes when zooming out far and grid expanding out is enabled

### ISSUE THREAD

**Issue by Minh-Than** [oriedita/oriedita#299]

**Comment by Minh-Than** [comment]
An idea I have is to have it zoom out where it the more inner grids get faded out into nothing and it repeats like that as you zoom out.
An example is this one gif I found in this [site](https://www.boristhebrave.com/2023/01/28/infinite-quadtrees-fractal-coordinates/)
![quadtree1_zoom](https://user-images.githubusercontent.com/94136126/222978399-43ec096d-0aa4-47a1-b32a-118365228c11.gif)

**Comment by qurben** [comment]
An intermediate solution is probably just to draw the grid up to a specific density, this way it at least doesn't hang.

An infinite grid is also a really cool solution.
