### ISSUE TITLE
Include Opaque X-ray like what Oripa has

### ISSUE THREAD

**Issue by Minh-Than** [oriedita/oriedita#308]
Would be nice if this kind of X-ray is added in.
![image](https://user-images.githubusercontent.com/94136126/223558644-bf195a50-dcf0-4cde-9f5e-9d99920b66af.png)

Edit: I've been told that there is such an x-ray in Oriedita but it's only a bit similar with black borders and light layering opacity strength. I prefer the Oripa version more and I'd like for that version to be added (Either as an option on the setting page or in the panel).

**Comment by qurben** [comment]
This?
![Oriedita_2023-03-07_22-39-07](https://user-images.githubusercontent.com/589651/223558944-48b9df30-39d2-4ae3-b579-8fe9041bfa64.png)

**Comment by Minh-Than** [comment]
Damn I'm blind. Then maybe a version that has no border.

**Comment by Minh-Than** [comment]
Update: apparently I just haven't used Edita enough because found this (x-ray view -> colored -> increase transparency to the max)
<img width="442" alt="image" src="https://user-images.githubusercontent.com/94136126/225498497-747ae399-e5e9-48ca-896d-6cb016728c9d.png">

I will now close this issue and cry in a corner for a bit.
