### ISSUE TITLE
Yellow warning very difficult to read in Light Mode

### ISSUE THREAD

**Issue by TabLand** [oriedita/oriedita#330]
Previously only tested with Dark Mode. A more appropriate colour is required.

![image](https://github.com/oriedita/oriedita/assets/2546543/8b192c5d-03bd-40b7-b64d-e87dd965ea53)

**Comment by origamifaust** [comment]
Red should be fine i think on light mode.

**Comment by undertrox** [comment]
True, orange sounds like a good idea as long as it's dark enough

**Comment by TabLand** [comment]
@origamifaust mentioned that it would add value to move this warning to the top row, as it's currently blocking a useful section of the drawing window
