### ISSUE TITLE
.fold format exports incomplete?

### ISSUE THREAD

**Issue by TabLand** [oriedita/oriedita#347]
I get the following error when I try to import an Oriedita .fold export into https://origamisimulator.org/:

```
Invalid FOLD file, must contain all of:

vertices_coords
edges_vertices
edges_assignment
faces_vertices
```
Upon checking the file export, `faces_vertices` is missing

**Comment by qurben** [comment]
In a FOLD file almost every field is recommended and not required. The FOLD files that are exported by oriedita currently only define edges and vertices as this is the main thing that oriedita reasons about. 

To support origamisimulator FOLD files we would need to also export faces information in the fold files.
