### ISSUE TITLE
Fix precision errors in detailed crease patterns

### ISSUE THREAD

**Issue by qurben** [oriedita/oriedita#36]
When creasepatterns are too small floating point errors and rendering artifacts occur when folding. This can be prevented by making sure that the starting creasepattern is sufficiently large.

By default .cp files are 400x400 

About 10k by 10k should be ok. Maybe come up with a justified number.

**Comment by MuTsunTsai** [comment]
Typically for a geometry-related program like this, it will have a hard-coded epsilon somewhere as a threshold of deciding if two numbers are considered identical. But apparently there's no "epsilon" in the source code by a quick search. Meguro probably called it something else. This will take time to look into.

**Comment by qurben** [comment]
The choices are probably kinda arbitrary, and they are used for different purposes.
