### ISSUE TITLE
Folding with multiple squares freezes the program

### ISSUE THREAD

**Issue by undertrox** [oriedita/oriedita#74]
pressing fold when there are multiple squares in a file will freeze the program, so that it can only be quit using the task manager. In the original orihime, it only makes the folding thread run indefinitely, but you can still stop it using the brake button.

**Comment by qurben** [comment]
Thanks for letting me know, the reason this freezes the program is that the console is part of the GUI and the folding algorithm will spam stdout when it gets into a wrong state caused by folding multiple sheets at once.
